---
name: Data-Structure-Util
version: 0.13
author:
  - 'This release by Andy Armstrong <andy@hexten.net>'
  - 'Originally by Pierre Denis <pdenis@fotango.com>'
abstract: Change nature of data within a structure
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Digest::MD5: 0
  perl: 5.6.0
build_requires:
  Clone: 0
  Scalar::Util: 1.01
  Test::More: 0
  Test::Pod: 0
  Test::Simple: 0
dynamic_config: 0
provides:
  Data::Structure::Util:
    file: lib/Data/Structure/Util.pm
    version: 0.13
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
